FROM openjdk:11
COPY ./target/user-authentication-management-0.0.1-SNAPSHOT.jar user-authentication-management-0.0.1-SNAPSHOT.jar
EXPOSE 8089
CMD ["java", "-jar", "user-authentication-management-0.0.1-SNAPSHOT.jar"]